### PR TITLE
Added additional information on chaining async in-line actions

### PR DESCRIPTION
**Pull request by krlicmuhamed**
It needs a little bit of rewriting... But this basically explains how to chain many `action.run`s inside a main action

### CODE REVIEW

**Comment by evantahler** [comment]
Thanks for the example!  

I think this can be improved - This is a pretty large example.  Also, it's generally bad practice to combine promise responses (`.then()`) and async functions... it leads to confusion.  Would something like the following work to make the point more concisely?

```ts
import { action, Action } from "actionhero";

export class ActionA extends Action {
  constructor() {
    super();
    this.name = "First Action";
  }

  async run() {
    return { firstResponse: "ok" };
  }
}

export class ActionB extends Action {
  constructor() {
    super();
    this.name = "Second Action";
  }

  async run() {
    const firstResponse = await action.run("First Action");
    const secondResponse = { secondResponse: "ok" };
    return Object.assign(firstResponse, secondResponse); // returns { firstResponse: "ok", secondResponse: "ok" }
  }
}
```

**Comment by krlicmuhamed** [comment]
In my example I use 3 actions to generate data for one whole action, each one depends on the other. What you gave in example is already written. I don't know If you understand my point, I use 3 actions first one is Does User Exist if so then continue with Adding User to database and If that action passes I want to Add Device action to add a device to the database. So each action depends on the data that is passed in that case we need to write _async_ success callback so we can call `await action.run("Next Action")`

**Comment by evantahler** [comment]
I think I am confused about what you are trying to accomplish! 

Would looking at the response of each run accomplish what you need?
```ts
const response1 = await action.run(...)
if (response1.madeNewUser) await action.run(...)
```

**Comment by evantahler** [comment]
Closing due to lack of comment.

**Pull request closed without merging**
